---
title: "workflow"
output: word_document
date: "2024-12-19"
---

```{r}
library(usethis)
use_github()

```

#PCA exploratorie
```{r}
library(readxl)
library(tidyverse)

Results_final_toate_cu_erori <- read_excel("Results_final_toate_cu_erori.xlsx", 
    sheet = "RSD<10%")
df <- as_tibble(Results_final_toate_cu_erori) |> 
  mutate_if(is.character, as.factor)

library(factoextra)
library(FactoMineR)

pca_df <- PCA(df[,3:13], graph = FALSE, scale.unit = TRUE)

fviz_pca_biplot(pca_df, geom = "point", 
                ol.var = "black", 
    col.ind = df$SITE, 
    shape.ind = df$SITE, 
    pointsize = 1.5,
    legend.title = "Groups", 
    addEllipses = F, 
    ellipse.level = 0.95, 
    label = "var", 
    habillage = df$SITE, 
    ggtheme = theme_minimal(), 
    title = "PCA", repel = TRUE)

df2 <- df |> 
  filter(!SITE == "HOIS argile") |> 
    filter(!SITE == "HOIS placute")
```

#PCA
```{r}
pca_df2 <- PCA(df_clean[,3:13], graph = FALSE, scale.unit = TRUE)

fviz_pca_biplot(pca_df2, geom = "point", 
                col.var = "black", 
                col.ind = df_clean$SITE, 
                shape.ind = df_clean$SITE, 
                pointsize = 1.5,
                legend.title = "Groups", 
                addEllipses = F, 
                ellipse.level = 0.95, 
                label = "var", 
                habillage = df_clean$SITE, 
                ggtheme = theme_minimal(),
                title = "PCA", repel = TRUE)
```

#LOF
```{r}
library(dbscan)
lof_scores <- lof(df2[,3:13], minPts = nrow(df2)/5)

hist(lof_scores, breaks = 100, col = "skyblue", border = "white", 
     xlab = "Local Outlier Factor (LOF)", 
     main = "Histogram of LOF scores")

df2$lof_scores <- lof_scores

ggplot(df2, aes(x = 1:nrow(df2), y = lof_scores, fill = SITE, color = SITE)) +
  geom_point() +
  geom_text(aes(label = SITE), vjust = -0.5) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

threshold <- 1.5
df2$outliers <- as.factor(ifelse(lof_scores > threshold, "Outlier", "Inlier"))

df_clean <- filter(df2, !outliers == "Outlier")

```


```{r}
library(viridis)

plot_Ti_vs_Zr <- df2 |> 
  ggplot(aes(x = Ti_avg, 
             y = Zr_avg 
             )
         ) +
  geom_point(
    aes(colour = SITE, 
             shape = SITE),
    show.legend = T, 
    size = 3
             ) +
  geom_text(aes(label = SITE),
                ) + 
  labs(title = "Grafic 7. Vizualizarea clusterilor în funcție de raportul Zr/Ti") +
  scale_color_viridis(option = "H", discrete = T)
 
plot_Ti_vs_Zr

library(ggstatsplot)
df_tst <- df2 |> 
  gather(key = "Element", value = "Concentratie", 3:13) |>     
  mutate_if(is.character, as.factor) |> 
  unite("Element_Site", Element, SITE, sep = "_", remove = F) |> 
  mutate_if(is.character, as.factor)

grouped_ggbetweenstats(data = df_tst, 
                       x = SITE, 
                       y = Concentratie, 
                       grouping.var = Element, 
                       type = "np",
                       #pairwise.display = "significant",
                       ggsignif.args = list(textsize = 2, tip_length = 0.01),
                       p.adjust.method = "fdr",
                       #conf.level = NULL,
                       plotgrid.args = list(ncol = 2),
                       annotation.args = list(title = "Grafic 5. Analiza comparativă a concentrațiilor elementelor în funcție de clusteri")
                        )
library(lmPerm)

model_clusters <- aovp(Al2O4_avg + SiO3_avg + K2O_avg + Ca_avg + Ti_avg + Mn_avg + Fe_avg + Zn_avg + Rb_avg + Sr_avg + Zr_avg ~ SITE,
             center = F,
             seqs = F,
             maxIter = 1e6,
             data = df2, 
             perm = "Exact"
             )
summary.lmp(model_clusters)
summary.aovp(model_clusters)

library(tidyverse)

df_centr <- df2 |> as.data.frame() |> 
  mutate_at(3:13, scale) |> 
  unite("Proba_Site", SITE:SAMPLE, sep = "_", remove = F)

df_centr <- data.frame(df_centr, row.names = )

library(hopkins)
indice_grupare <- hopkins(df_centr[3:13], m = nrow(df_centr) / 2)
indice_grupare

library(factoextra)
fviz_dist(dist(df_centr[3:13], 
               method = "minkowski"
               ), 
          gradient = list(
            low = "blue", 
            mid = "white", 
            high = "red"
            )
          ) +
  labs(title = "Grafic 3. Matricea de distanțe între probele analizate",
       subtitle = "Indice Hopkins: 0,88")

clust_res <- eclust(df_centr[3:13], 
                    FUNcluster = "hclust", 
                    k = NULL,
                    graph = T,
                    hc_metric = "minkowski",
                    hc_method = "ward.D2"
                    )

fviz_dend(clust_res) +
  labs(title = "Grafic 4. Dendograma rezultată în urma partiționării în clusteri") +
  scale_color_viridis(option = "H", discrete = T)

library(clValid)

distance_matrix <- get_dist(df_centr[,3:13], "minkowski")

distance_matrix <- as.matrix(distance_matrix)

validare <- clValid(distance_matrix, 2:8, clMethods = c("agnes"), validation = c("internal", "stability"))
summary(validare)

clust_2 <- eclust(df_centr[,3:13],
                  FUNcluster = "hclust",
                  k = 3,
                  graph = T,
                  hc_metric = "minkowski",
                  hc_method = "ward.D2"
                  )
fviz_cluster(clust_2, repel = T) +
  scale_color_viridis(option = "H", discrete = T)


fviz_dend(clust_2, rect = T) +
  labs(title = "Grafic 4. Dendograma rezultată în urma partiționării în clusteri") +
  scale_color_viridis(option = "H", discrete = T)
```
